FROM golang:1.15.6 as builder

WORKDIR /app

COPY chat-api/go.mod chat-api/go.sum ./
RUN go mod download

COPY chat-api/. .
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/chat_api

FROM alpine:3.10.1
WORKDIR /app

RUN apk update \
    && apk add --no-cache libc6-compat

EXPOSE 8000
EXPOSE 8080
COPY --from=builder /app/main .
CMD ["./main"]