FROM golang:1.15.6-alpine

WORKDIR /go/src/go-chat-app-api-ver/web-server

ENV PASSWORD1=password

RUN apk update \
    && apk add --no-cache \
        alpine-sdk \
        git \
    && go get github.com/pilu/fresh

COPY web-server/go.mod web-server/go.sum ./
RUN go mod download

COPY web-server/. .


EXPOSE 80

CMD ["fresh"]