use db_chats;

CREATE TABLE ROOM_STRUCTS_OF_CHAT (
    ID INT(11) AUTO_INCREMENT NOT NULL,
    USER_ID VARCHAR(10) NOT NULL,
    ROOM_NAME VARCHAR(20) NOT NULL,
    MEMBER VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (USER_ID, ROOM_NAME, MEMBER)
);

CREATE TABLE ALL_STRUCTS_OF_CHAT (
    ID INT(11)  NOT NULL,
    USER_ID VARCHAR(10) NOT NULL,
    ROOM_NAME VARCHAR(20) NOT NULL,
    MEMBER VARCHAR(10) NOT NULL,
    CHAT VARCHAR(255) NOT NULL,
    POST_DT DATETIME NOT NULL
);