use db_users;

CREATE TABLE USERS (
    USER_ID VARCHAR(10) NOT NULL,
    PASSWORD BLOB NOT NULL
);

CREATE TABLE SESSIONS (
    SESSION_ID VARCHAR(44) NOT NULL,
    SESSION_VALUE VARCHAR(10) NOT NULL
);